#!/usr/bin/env bash

export PATH=$PATH:$HOME/local/mongo/bin
export PATH=$PATH:$HOME/local/redis/bin
export PATH=$PATH:$HOME/bin
export PATH=$PATH:$HOME/local/node/bin
export PATH=$PATH:$HOME/local/jscoverage/bin
export PATH=$PATH:/usr/local/sbin
export PATH=$PATH:/usr/local/share/npm/bin

export REDIS_DATA_DIR=/data/redis

export GOROOT=/usr/local/Cellar/go/1.10.2/libexec/
export PATH=$PATH:$GOROOT/bin
export GOPATH=$HOME/Sites/go
export PATH=$PATH:$GOPATH/bin

export CHANGER_OPS=$HOME/Sites/sc-ops
